name: Generate Snake

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: Jaovitorlm
          entryPoint: generate-snake
          args: '--snake-color="#0000FF" --dot-color="#FFFFFF"'

